import { readFile } from "fs/promises";
import path from "path";
import { describe, expect, it } from "vitest";
import { PRODUCE_PHASES } from "./pipeline";

describe("produce order", () => {
  it("writes the composition html after music and before assemble", () => {
    expect([...PRODUCE_PHASES]).toEqual(["copy", "board", "images", "speech", "music", "html", "assemble"]);
  });

  it("imports generateCloneStill before rendering person stills", async () => {
    const pipeline = await readFile(path.join(process.cwd(), "src/lib/pipeline.ts"), "utf8");
    expect(pipeline).toMatch(/import \{ generateCloneStill \} from "\.\/flow\/image"/);
    expect(pipeline).toMatch(/talkStillRefPaths/);
    expect(pipeline).toMatch(/startRetry/);
  });
});

describe("c-end copy has no vendor names", () => {
  it("keeps the homepage and produce messages vendor-free", async () => {
    const root = path.join(process.cwd(), "src");
    const page = await readFile(path.join(root, "app/page.tsx"), "utf8");
    const pageCss = await readFile(path.join(root, "app/page.module.css"), "utf8");
    const nav = await readFile(path.join(root, "app/site-nav.tsx"), "utf8");
    const talks = await readFile(path.join(root, "app/talks/page.tsx"), "utf8");
    const workspace = await readFile(path.join(root, "app/talk-workspace.tsx"), "utf8");
    const talkDetail = await readFile(path.join(root, "app/talks/[id]/page.tsx"), "utf8");
    const assist = await readFile(path.join(root, "app/talk-assist.tsx"), "utf8");
    const assistRecs = await readFile(path.join(root, "app/assist-caption-recs.tsx"), "utf8");
    const assistGfx = await readFile(path.join(root, "app/assist-graphic-recs.tsx"), "utf8");
    const pipeline = await readFile(path.join(root, "lib/pipeline.ts"), "utf8");
    const cover = await readFile(path.join(root, "lib/cover.ts"), "utf8");
    const coverTemplates = await readFile(path.join(root, "lib/cover-templates.ts"), "utf8");
    const captionStyles = await readFile(path.join(root, "lib/caption-styles.ts"), "utf8");
    const copy = await readFile(path.join(root, "lib/copy.ts"), "utf8");
    const speech = await readFile(path.join(root, "lib/flow/speech.ts"), "utf8");
    const homeWall = await readFile(path.join(root, "app/home-wall.tsx"), "utf8");
    const visible = [page, nav, talks, talkDetail, workspace, assist, assistRecs, assistGfx, pipeline, cover, coverTemplates, captionStyles, copy, speech, homeWall].join("\n");
    expect(visible).toMatch(/开始做/);
    expect(visible).toMatch(/我的视频/);
    expect(visible).toMatch(/在写合成稿/);
    expect(visible).toMatch(/确认后再写故事分镜/);
    expect(visible).toMatch(/在备组件图/);
    expect(visible).toMatch(/确认故事分镜，开始出图/);
    expect(visible).toMatch(/正在写口播文案/);
    expect(visible).toMatch(/人物形象/);
    expect(visible).toMatch(/重做这张/);
    expect(visible).toMatch(/八个方位/);
    expect(visible).toMatch(/确认文案，写故事分镜/);
    expect(workspace).toMatch(/正在写故事分镜/);
    expect(workspace).toMatch(/重写故事分镜/);
    expect(homeWall).toMatch(/待确认故事分镜/);
    expect(page).toMatch(/默认电影大片/);
    expect(workspace).toMatch(/LETTERING_MODE_LABEL/);
    expect(visible).toMatch(/确认故事分镜，开始出图/);
    expect(visible).toMatch(/先写文案/);
    expect(page).toMatch(/goGhost/);
    expect(talks).toMatch(/MineMasonry/);
    expect(visible).toMatch(/对照/);
    expect(visible).toMatch(/确认画面，继续成片/);
    expect(visible).not.toMatch(/微调成片/);
    expect(visible).toMatch(/再出一次片/);
    expect(visible).toMatch(/重新生成封面/);
    expect(visible).toMatch(/选封面模版/);
    expect(visible).toMatch(/做成封面/);
    expect(visible).toMatch(/杂志字/);
    expect(visible).toMatch(/霓虹字/);
    expect(workspace).toMatch(/CoverStylePreview/);
    expect(workspace).toMatch(/CaptionStylePreview/);
    expect(workspace).toMatch(/resolveCaptionStyle/);
    expect(workspace).toMatch(/onBoard/);
    expect(visible).toMatch(/全片字幕/);
    expect(talkDetail).toMatch(/TalkAssistPanel/);
    expect(talkDetail).toMatch(/styles\.layout/);
    expect(talkDetail).toMatch(/styles\.rail/);
    expect(talkDetail).toMatch(/styles\.talkFrame/);
    expect(assist).toMatch(/AssistMarkdown/);
    expect(assist).toMatch(/AssistCaptionRecCards/);
    expect(assist).toMatch(/AssistGraphicRecCards/);
    expect(assist).toMatch(/recommendations/);
    expect(assist).toMatch(/有哪些字幕推荐/);
    expect(assist).toMatch(/有哪些组件推荐/);
    expect(assist).toMatch(/\/assist/);
    expect(assist).toMatch(/assist-graphic/);
    expect(assist).toMatch(/用到全片/);
    expect(assistRecs).toMatch(/用到这一镜/);
    expect(assistRecs).toMatch(/用到全片/);
    expect(assist).not.toMatch(/DeepSeek|GPT|方舟|HyperFrames/i);
    expect(pageCss).toMatch(/assistRail/);
    expect(pageCss).toMatch(/assistBubbleBot/);
    expect(pageCss).toMatch(/\.talkFrame/);
    expect(pageCss).toMatch(/\.assistMd/);
    expect(pageCss).toMatch(/assistStageRecs/);
    expect(pageCss).toMatch(/assistGfxPreview/);
    expect(pageCss).toMatch(/assistGfxList/);
    expect(pageCss).toMatch(/assistGfxMotFlash/);
    expect(pageCss).toMatch(/assistGfxCarousel/);
    expect(assistGfx).toMatch(/assistGfxMotCarousel|detectFx|GraphicFxStage/);
    expect(workspace).toMatch(/styles\.talkWork/);
    expect(workspace).toMatch(/assistRecommendations/);
    expect(workspace).toMatch(/assistGraphics/);
    expect(workspace).toMatch(/AssistCaptionRecCards/);
    expect(workspace).toMatch(/AssistGraphicRecCards/);
    expect(talkDetail).toMatch(/assistRecommendations/);
    expect(talkDetail).toMatch(/assistGraphics/);
    expect(visible).toMatch(/这条字幕/);
    expect(visible).toMatch(/选字幕样式/);
    expect(visible).toMatch(/用到全片/);
    expect(visible).toMatch(/只用这一条/);
    expect(visible).toMatch(/用到这一镜/);
    expect(visible).toMatch(/用到各镜/);
    expect(visible).toMatch(/有哪些组件推荐/);
    expect(visible).toMatch(/电影字/);
    expect(visible).toMatch(/粉笔字/);
    expect(visible).toMatch(/涂鸦字/);
    expect(visible).toMatch(/特效字/);
    expect(visible).toMatch(/打字机/);
    expect(visible).toMatch(/气质条/);
    expect(visible).toMatch(/珊瑚硬边/);
    expect(visible).toMatch(/双年展黄/);
    expect(visible).toMatch(/动效字/);
    expect(visible).toMatch(/闪烁扫过/);
    expect(visible).toMatch(/片卡字/);
    expect(visible).toMatch(/撞色字/);
    expect(visible).toMatch(/种草字/);
    expect(visible).toMatch(/更多字/);
    expect(visible).toMatch(/打乱露出/);
    expect(visible).toMatch(/网点字/);
    expect(workspace).toMatch(/FX_CAPTION_STYLES/);
    expect(workspace).toMatch(/FRAME_CAPTION_STYLES/);
    expect(workspace).toMatch(/MOVE_CAPTION_STYLES/);
    expect(workspace).toMatch(/CARD_CAPTION_STYLES/);
    expect(workspace).toMatch(/POP_CAPTION_STYLES/);
    expect(pageCss).toMatch(/capMotSlamHit/);
    expect(pageCss).toMatch(/capMotWipeReveal/);
    expect(pageCss).toMatch(/capMotShimmer/);
    const captionPreview = await readFile(path.join(process.cwd(), "src/app/caption-style-preview.tsx"), "utf8");
    expect(captionPreview).toMatch(/PREVIEW_SLAM_STACK/);
    expect(captionPreview).toMatch(/captionPreviewTokens/);
    expect(pageCss).toMatch(/prefers-reduced-motion/);
    expect(workspace).toMatch(/重试/);
    expect(visible).toMatch(/选中的克隆音色没接上|选中的克隆音色这次没接上|克隆音色通道还没开通/);
    expect(visible).toMatch(/在做封面/);
    expect(visible).not.toMatch(/Astra|Astro|GPT|gpt-6/i);
    expect(visible).not.toMatch(/HyperFrames|Seedream|Gemini|方舟|豆包|即梦/i);
    expect([nav, talks, workspace, page].join("\n")).not.toMatch(/数据库/);
  });
});

describe("home wall playback", () => {
  it("only keeps one wall video playing", async () => {
    const wall = await readFile(path.join(process.cwd(), "src/app/home-wall.tsx"), "utf8");
    expect(wall).toMatch(/playingId/);
    expect(wall).toMatch(/setPlayingId\(row\.id\)/);
    expect(wall).toMatch(/querySelectorAll\("video"\)/);
    expect(wall).not.toMatch(/我做的/);
    const wallCard = wall.slice(wall.indexOf("function WallCard"), wall.indexOf("function MineCard"));
    expect(wallCard).not.toMatch(/<strong>/);
  });
});
